### PR TITLE
removed user_data field from config and removed openCV imports to speed up travis

### PR DESCRIPTION
**Pull request by nskh**
## What do these changes do?

I removed the `user_data` field within `config` that I added earlier for Flow parameter export, since now it gets stored in `flow_params.json`. I also removed the OpenCV import statements that were slowing down Travis builds for Flow. This version of Ray still passes our `nose2` unit and integration tests.

### CODE REVIEW

**Review by cathywu — APPROVED** [review]
LGTM! nice clean PR, thanks for thinking of removing the earlier change!

**Comment by cathywu** [comment]
@nskh Let's watch for if the test on Travis fail or anything as a result of these changes. :) We should next be able to remove the opencv install step in the `.travis.yml` in `learning-traffic` and that should save 2 minutes per build.

**Comment by nskh** [comment]
@cathywu do you mean Travis tests in `learning-traffic` using this repo? Those should be fine, if they duplicate the nose2 tests we've got locally (in my understanding this is what happens).

**Comment by cathywu** [comment]
Yeah, I think so too! But it's good to keep an eye on it in case we missed
something.

Best wishes,
Cathy

**Comment by nskh** [comment]
Just restarted the Travis builds for Aboudy's [PR #254](https://github.com/cathywu/learning-traffic/pull/254) on `learning-traffic` (they were passing before). Should have an answer in a few minutes.

**Pull request merged**
